export const endPoints = {
    ganado: 'ganado/',
    todosGanado: 'ganado',
    toro: 'toro/',
    todosToro: 'toro',
    criasNumeracion: 'crias_pendiente_numeracion',
    criasCapar: 'crias_pendiente_capar',
    preciosLeche: 'precio',
    ventasLeche: 'venta_leche',
    insumo: 'insumo/',
    insumos: 'insumo',
    personal: 'personal/',
    todosPersonal: 'personal',
    comprador: 'comprador/',
    compradores: 'comprador',
    ventaGanado: 'ventas/',
    ventasGanado: 'ventas',
    fallecimiento: 'fallecimientos/',
    fallecimientos: 'fallecimientos',
    revisiones: 'revisiones',
    servicios: 'servicios',
    pesajesLeche: 'pesaje_leche',
    dashboardPrincipaltotalGanadoTipo: 'dashboard_principal/total_ganado_tipo',
    dashboardPrincipaltotalPersonal: 'dashboard_principal/total_personal',
    dashboardPrincipalvacasGestacion: 'dashboard_principal/vacas_gestacion',
    dashboardPrincipalvacasProductoras: 'dashboard_principal/vacas_productoras',
    dashboardPrincipalvacasMenosProductoras: 'dashboard_principal/vacas_menos_productoras',
    dashboardPrincipalpendienteRevision: 'dashboard_principal/ganado_pendiente_revision',
    dashboardPrincipalcantidadNovillasMontar: 'dashboard_principal/cantidad_novillas_montar',
    dashboardPrincipalinsumoMenorExistencia: 'dashboard_principal/menor_insumo',
    dashboardPrincipalinsumoMayorExistencia: 'dashboard_principal/mayor_insumo',
    dashboardPrincipalbalanceAnualLeche: 'dashboard_principal/balance_anual_leche',
    dashboardVentaLecheprecioActual: 'dashboard_venta_leche/precio_actual',
    dashboardVentaLechevariacionPRecio: 'dashboard_venta_leche/variacion_precio',
    dashboardVentaLechegananciasDelMes: 'dashboard_venta_leche/ganancias_mes',
    dashboardVentaLecheventasMesLeche: 'dashboard_venta_leche/ventas_mes',
    dashboardVentaGanadomejorComprador: 'dashboard_venta_ganado/mejor_comprador',
    dashboardVentaGanadomejorVenta: 'dashboard_venta_ganado/mejor_venta',
    dashboardVentaGanadopeorVenta: 'dashboard_venta_ganado/peor_venta',
    dashboardVentaGanadoventasMesGanado: 'dashboard_venta_ganado/venta_mes',
    dahboardFallecimientos: 'dashboard_fallecimientos/causas_frecuentes',
    notificaciones: 'notificaciones',
};

export const endPointsCattle = {
    revision: '/revision/',
    revisiones: '/revision',
    servicio: '/servicio/',
    servicios: '/servicio',
    parto: '/parto/',
    partos: '/parto',
    pesajeLeche: '/pesaje_leche/',
    pesajesLeche: '/pesaje_leche',
};