export const endPoints = {
    ganado: 'ganado/',
    todosGanado: 'ganado',
    toro: 'toro/',
    todosToro: 'toro',
    criasNumeracion: 'crias_pendiente_numeracion',
    criasCapar: 'crias_pendiente_capar',
    preciosLeche: 'precio',
    ventasLeche: 'venta_leche',
    insumo: 'insumo/',
    insumos: 'insumo',
    personal: 'personal/',
    todosPersonal: 'personal',
    comprador: 'comprador/',
    compradores: 'comprador',
    ventaGanado: 'ventas/',
    ventasGanado: 'ventas',
    fallecimiento: 'fallecimientos/',
    fallecimientos: 'fallecimientos',
    revisiones: 'revisiones',
    servicios: 'servicios',
    pesajesLeche: 'pesaje_leche',
    totalGanadoTipo: 'total_ganado_tipo',
    vacasProductoras: 'vacas_productoras',
    vacasMenosProductoras: 'vaca_menos_productoras',
    insumoMayorExistencia: 'menor_insumo',
    insumoMenorExistencia: 'mayor_insumo',
    balanceAnualLeche: 'balance_anual_leche',
    notificaciones: 'notificaciones',
};

export const endPointsCattle = {
    revision: '/response_revision/',
    revisiones: '/response_revisiones',
    servicio: '/response_servicio/',
    servicios: '/response_servicios',
    parto: '/response_parto/',
    partos: '/response_partos',
    pesajeLeche: '/response_pesajeLeche/',
    pesajesLeche: '/response_pesajesLeche',
};