export const endPoints = {
    ganado: 'ganado/',
    todosGanado: 'ganado',
    toro: 'toro/',
    crearUsuario:'register',
    todosToro: 'toro',
    todosReses: 'res',
    res: 'res/',
    criasNumeracion: 'crias_pendiente_numeracion',
    asignarNumeroCria: 'asignar_numero_cria/',
    criasCapar: 'crias_pendiente_capar',
    caparCria: 'capar_cria/',
    crearPrecioLeche:'precio/',
    preciosLeche: 'precio',
    ventasLeche: 'venta_leche',
    insumo: 'insumo/',
    insumos: 'insumo',
    personal: 'personal/',
    todosPersonal: 'personal',
    veterinariosDisponibles:'veterinarios',
    comprador: 'comprador/',
    compradores: 'comprador',
    ventaGanado: 'ventas/',
    ventasGanado: 'ventas',
    fallecimiento: 'fallecimientos/',
    fallecimientos: 'fallecimientos',
    revisiones: 'revisiones',
    servicios: 'servicios',
    partos: 'partos',
    pesajesLeche: 'pesaje_leche',
    cargosPersonal: 'cargos_personal',
    dashboardPrincipaltotalGanadoTipo: 'dashboard_principal/total_ganado_tipo',
    dashboardPrincipaltotalPersonal: 'dashboard_principal/total_personal',
    dashboardPrincipalvacasGestacion: 'dashboard_principal/vacas_gestacion',
    dashboardPrincipalvacasProductoras: 'dashboard_principal/vacas_productoras',
    dashboardPrincipalvacasMenosProductoras: 'dashboard_principal/vacas_menos_productoras',
    dashboardPrincipalpendienteRevision: 'dashboard_principal/ganado_pendiente_revision',
    dashboardPrincipalcantidadNovillasMontar: 'dashboard_principal/cantidad_novillas_montar',
    dashboardPrincipalinsumoMenorExistencia: 'dashboard_principal/menor_insumo',
    dashboardPrincipalinsumoMayorExistencia: 'dashboard_principal/mayor_insumo',
    dashboardPrincipalbalanceAnualLeche: 'dashboard_principal/balance_anual_leche',
    dashboardVentaLecheprecioActual: 'dashboard_venta_leche/precio_actual',
    dashboardVentaLechevariacionPRecio: 'dashboard_venta_leche/variacion_precio',
    dashboardVentaLechegananciasDelMes: 'dashboard_venta_leche/ganancias_mes',
    dashboardVentaLecheventasMesLeche: 'dashboard_venta_leche/ventas_mes',
    dashboardVentaGanadomejorComprador: 'dashboard_venta_ganado/mejor_comprador',
    dashboardVentaGanadomejorVenta: 'dashboard_venta_ganado/mejor_venta',
    dashboardVentaGanadopeorVenta: 'dashboard_venta_ganado/peor_venta',
    dashboardVentaGanadoventasMesGanado: 'dashboard_venta_ganado/venta_mes',
    dahboardFallecimientos: 'dashboard_fallecimientos/causas_frecuentes',
    notificaciones: 'notificaciones',
    fechaUltimoRespaldo:'ultimo_respaldo'
};

export const endPointsCattle = {
    revision: '/revision/',
    revisiones: '/revision',
    servicio: '/servicio/',
    servicios: '/servicio',
    parto: '/parto/',
    partos: '/parto',
    pesajeLeche: '/pesaje_leche/',
    pesajesLeche: '/pesaje_leche',
};

/**Rutas para el endpoint de laravel   */
export const endpointsReports={
    venta_leche:'reportes/venta_leche',
    fallecimiento:'reportes/fallecimiento',
    dashboard:'reportes/general',
    ganado:'reportes/ganado'
}
/**Rutas para el endpoint de laravel   */
export const endpointsReportsAnnual={
    venta_ganado:'reportes/venta_ganado',
}