import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Navbar } from "@/components/navbar";
import { Sidebar } from "@/components/sidebar";
import { StyledEngineProvider } from "@mui/material";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={`${nunito.className} grid grid-cols-12`}>
        <header className="col-span-2">
          <Sidebar android={false} />
        </header>
        <nav className="col-span-full sm:col-start-3 sm:col-end-12">
          <Navbar />
        </nav>
        
        <AppRouterCacheProvider>
          <StyledEngineProvider injectFirst>
            <main className="col-start-2 col-span-full">{children}</main>
          </StyledEngineProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
