import type { Metadata } from 'next';

import './globals.css';
import { Navbar } from '@/components/navbar';
import { Sidebar } from '@/components/sidebar';
import { Providers } from './providers';
import localFont from 'next/font/local';


const bebasNue = localFont({
    src: '../../public/fonts/BebasNeue-Regular.ttf',
    display: 'swap',
    variable:'--font-bebasNue'
});

const nunito = localFont({
    src: '../../public/fonts/nunito-latin-400-normal.ttf',
    display: 'swap',
    variable:'--font-nunito'
});


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    modal,
}: {
    children: React.ReactNode;
    modal: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme={'ganadexThemeDark'} className="dark">
            <body
                className={`${nunito.variable} ${bebasNue.variable} font-nunito grid grid-cols-12   bg-background dark:bg-background-dark`}
            >
                <header className="col-span-2">
                    <Sidebar android={false} />
                </header>
                <nav className="col-span-full z-50 sm:col-start-3 sm:col-end-12 lg:translate-x-6">
                    <Navbar />
                </nav>

                <main className="mt-2 sm:col-start-2 lg:mt-0 lg:col-start-3 col-span-full ">
                    <Providers>{children}
                    {modal}</Providers>
                </main>
            </body>
        </html>
    );
}
